name: Laforge agent

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - assigned
    branches:
      - main
      - master
  pull_request_review:
    types:
      - submitted
      - edited
  pull_request_review_comment:
    types:
      - created
      - edited
  issue_comment:
    types:
      - created
      - edited

jobs:
  agent:
    if: github.event_name == 'pull_request' || github.event.issue.pull_request
    runs-on: laforge-2
    container:
      image: laforge-2:latest
      env:
        MODELNAME: claude-sonnet-4-5-20250929
      volumes:
        - laforge-2_claude-config:/home/laforge/.claude-laforge
    steps:
      - name: Get PR details (for issue_comment events)
        if: github.event_name == 'issue_comment'
        id: pr
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            core.setOutput('number', context.issue.number);
            core.setOutput('head_ref', pr.data.head.ref);
            return pr.data.assignees.map(a => a.login).includes('laforge');

      - name: Check assignee condition and sender
        id: assignee-check
        if: |
          (github.event.sender.login != 'laforge') &&
          ((github.event_name == 'pull_request' && contains(github.event.pull_request.assignees.*.login, 'laforge')) ||
          (github.event_name == 'issue_comment' && steps.pr.outputs.result == 'true'))
        run: echo "Condition met, proceeding..."

      - name: Checkout code
        if: steps.assignee-check.conclusion == 'success'
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.event_name == 'issue_comment' && format('refs/pull/{0}/head', github.event.issue.number) || github.ref }}

      - name: Init .pr directory
        if: steps.assignee-check.conclusion == 'success'
        run: mkdir -p .pr

      - name: Create .pr/history.md
        if: steps.assignee-check.conclusion == 'success'
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_API_URL: ${{ gitea.api_url }}
          GITEA_REPO_OWNER: ${{ gitea.repository_owner }}
          GITEA_REPO_NAME: ${{ gitea.repository }}
          PR_INDEX: ${{ github.event_name == 'issue_comment' && steps.pr.outputs.number || github.event.pull_request.number }}
        run: node .gitea/workflows/fetch-pr.js

      - name: Run agent
        if: steps.assignee-check.conclusion == 'success'
        run: |
          echo "Running Claude agent..."
          claude.sh
          echo "Agent completed."

      - name: Commit and push changes
        if: steps.assignee-check.conclusion == 'success'
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_API_URL: ${{ gitea.api_url }}
        run: |
          # Configure git
          git config user.name "Laforge agent"
          git config user.email "laforge@tomyedwab.com"

          # Stage all changes except special files
          git add .
          git reset HEAD .pr/history.md .pr/status.yaml .pr/status.md .pr/commit.md 2>/dev/null || true

          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          # Determine commit message
          if [ -f .pr/commit.md ]; then
            COMMIT_MSG=$(cat .pr/commit.md)
          else
            COMMIT_MSG="Agent: updating PR status"
          fi

          # Derive base git URL from API URL (remove /api/v1 suffix)
          GIT_BASE_URL=$(echo "$GITEA_API_URL" | sed 's|/api/v1.*$||')

          # Commit and push
          git commit -m "$COMMIT_MSG"
          git push http://laforge:${GITEA_TOKEN}@${GIT_BASE_URL#http://}/${{ gitea.repository }}.git HEAD:${{ github.event_name == 'issue_comment' && steps.pr.outputs.head_ref || github.event.pull_request.head.ref }}

      - name: Install workflow dependencies
        if: steps.assignee-check.conclusion == 'success'
        run: |
          cd .gitea/workflows
          npm install

      - name: Post status to PR
        if: steps.assignee-check.conclusion == 'success'
        env:
          GITEA_TOKEN: ${{ secrets.LAFORGE_TOKEN }}
          GITEA_API_URL: ${{ gitea.api_url }}
          GITEA_REPO_OWNER: ${{ gitea.repository_owner }}
          GITEA_REPO_NAME: ${{ gitea.repository }}
          PR_INDEX: ${{ github.event_name == 'issue_comment' && steps.pr.outputs.number || github.event.pull_request.number }}
        run: node .gitea/workflows/post-status.js
